name: 'Semantic Version Increment'
description: 'Take in a version number and a flag that dictates which component number is to be incremented.'
inputs:
  current_version:  # id of input
    description: 'The current version number'
    required: true
  issue_type:
    description: 'The type of issue, to be used for incrementing the version number.'
    required: true
outputs:
  new_version: # id of output
    description: 'The incremented version number'
runs:
  using: 'node16'
  main: 'index.js'